### ISSUE TITLE
Scene loading at the start of the engine

### ISSUE THREAD

**Issue by Needlesslord** [Chamfer-Studios/Dune-Special-Spice-Ops#10]
**Describe the bug:** A clear and concise description of what the bug is.
_When you first start the engine (I started it on a computer in uni), the scene "0_level" is already there. It's not an empty new version_

**To Reproduce:** Steps to reproduce the behavior.
1. Open the engine

**Expected behavior:** A clear and concise description of what you expected to happen. 
_It should load a new empty unsaved scene_

**Additional context:** Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
_It happened on a computer in university_

**Comment by Montuuh** [comment]
That's a feature in the engine. Head to File ->Settings -> Scene Manager. You can see a Default Scene input text. Here you can set a scene that will open by default every time.
