### ISSUE TITLE
Keys counterintuitive

### ISSUE THREAD

**Issue by Needlesslord** [Chamfer-Studios/Dune-Special-Spice-Ops#13]
**Describe the bug:** A clear and concise description of what the bug is.
_W is selected to move_
_E is selected to rotate_
_R is selected to scale_

**To Reproduce:** Steps to reproduce the behavior.
1. Click on 'R' to scale
2. Click on 'E' to rotate
3. Click on 'W' to move

**Expected behavior:** A clear and concise description of what you expected to happen. 
_It would be better if_
1. Click on 'E' to scale
2. Click on 'R' to rotate
3. Click on 'W' to move

**Additional context:** Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
_-none-_

**Comment by Montuuh** [comment]
We wanted to follow Unity conventions, so we copied their keybinding in terms of transform.
